In [2]:
import numpy as np


In [3]:
#1
a = np.pad(np.zeros((8,8)), pad_width=1,mode='constant', constant_values=1)
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
#2
a = (np.arange(64).reshape(8,-1) // 8 + np.arange(8)) % 2
print(a)
#для нечетного можно вообще проще - остаток брать

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#3
a = np.diag(np.arange(1,5), -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [6]:
#4
a = np.random.random((10,3))
mins = a[np.arange(10), np.argmin(np.abs(a-0.5), axis = 1)]
print(a,"\n\n", mins)

[[0.04666553 0.87151671 0.63855015]
 [0.16036799 0.93444696 0.17369475]
 [0.61947296 0.46051063 0.01539703]
 [0.27894262 0.70253384 0.43177646]
 [0.34011478 0.60662881 0.71997421]
 [0.1239564  0.53858432 0.53324837]
 [0.07380047 0.6406258  0.8486291 ]
 [0.15348459 0.77223108 0.20385413]
 [0.41229741 0.60416496 0.10434683]
 [0.96190217 0.15093089 0.24695085]] 

 [0.63855015 0.17369475 0.46051063 0.43177646 0.60662881 0.53324837
 0.6406258  0.77223108 0.41229741 0.24695085]


In [16]:
#5
a = np.random.random((5,5))
a = a - np.mean(a, axis = 1).reshape(-1,1)
print(a)
print(np.mean(a, axis = 1))

[[ 0.18076966 -0.31494843  0.02780097  0.55046959 -0.44409179]
 [ 0.39735102 -0.16460939  0.14806606 -0.23990845 -0.14089924]
 [ 0.3816217  -0.1480181  -0.19303269 -0.01826786 -0.02230306]
 [ 0.33891533 -0.32491429  0.38576635  0.1150214  -0.51478879]
 [-0.09348024 -0.44076725  0.0583081   0.24573222  0.23020717]]
[0.00000000e+00 3.33066907e-17 0.00000000e+00 0.00000000e+00
 0.00000000e+00]


In [11]:
#6
a = np.random.random((6,6))
b = np.sum(a, axis = 1) / np.max(a, axis = 0)
print(a, "\n\n", b)

[[0.81934605 0.87872672 0.74330036 0.38690248 0.99295368 0.19310253]
 [0.46595724 0.0275922  0.92252971 0.36787498 0.07531887 0.55519729]
 [0.71475045 0.38524654 0.60516437 0.69432782 0.37334228 0.81894564]
 [0.31972183 0.12745441 0.00588668 0.61831422 0.69373126 0.85213351]
 [0.02658954 0.26748114 0.76742942 0.1381857  0.16517163 0.05361565]
 [0.3956701  0.70897772 0.63447319 0.39177711 0.6070544  0.861706  ]] 

 [4.8994339  2.74769192 3.89339991 3.76946137 1.42853902 4.17736272]


In [12]:
#7
# понятное решение
# x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
# mask = np.roll(x == 0, 1)
# mask[0] = 0
# res = np.max(x[mask])
# print(res)

# в одну строчку)
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result = np.max(x[(mask := np.concatenate(([False], (x == 0)[:-1])))])
print(result)


5


In [13]:
#8
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength = np.size(x))
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [18]:
#9
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
result = b[np.abs(a[:, :, None] - b).argmin(axis=-1)]
print(result)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


In [17]:
#10
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
res = np.convolve(a, np.ones(3)/3, mode='valid')
print(res)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
